NIS2_MAPPING = {
    "Art. 21(2)(a) – Risikoanalyse & IS-Sicherheitsrichtlinien": {
        "beschreibung": "Richtlinien zur Risikoanalyse und Sicherheit der Informationssysteme",
        "controls": ["5.1", "5.2", "5.3", "6.1", "8.2", "8.3"],
    },
    "Art. 21(2)(b) – Incident Handling": {
        "beschreibung": "Prozesse und Verfahren zur Behandlung von Sicherheitsvorfällen",
        "controls": ["5.24", "5.25", "5.26", "5.27", "5.28"],
    },
    "Art. 21(2)(c) – Business Continuity & DR": {
        "beschreibung": "BCM, Backup-Management, Disaster Recovery, Krisenmanagement",
        "controls": ["5.29", "5.30", "8.13", "8.14"],
    },
    "Art. 21(2)(d) – Lieferkettensicherheit": {
        "beschreibung": "Sicherheit in Lieferanten- und Drittanbieter-Beziehungen",
        "controls": ["5.19", "5.20", "5.21", "5.22", "5.23"],
    },
    "Art. 21(2)(e) – Sichere Entwicklung & Beschaffung": {
        "beschreibung": "Sicherheit bei Erwerb, Entwicklung und Wartung von Netz- und IS",
        "controls": ["8.25", "8.26", "8.27", "8.28", "8.29", "8.30", "8.31", "8.32"],
    },
    "Art. 21(2)(f) – Wirksamkeitsbewertung": {
        "beschreibung": "Bewertung der Wirksamkeit der Cybersicherheits-Risikomanagement-Maßnahmen",
        "controls": ["5.35", "5.36", "8.8", "9.1"],
    },
    "Art. 21(2)(g) – Cyber-Hygiene & Schulung": {
        "beschreibung": "Grundlegende Cyber-Hygiene-Praktiken und Cybersicherheitsschulungen",
        "controls": ["6.3", "6.8"],
    },
    "Art. 21(2)(h) – Kryptographie": {
        "beschreibung": "Richtlinien und Verfahren zum Einsatz von Kryptographie",
        "controls": ["8.24"],
    },
    "Art. 21(2)(i) – HR-Sicherheit, Zugang, Asset-Management": {
        "beschreibung": "Personalsicherheit, Zugangskontrollen, Asset-Management",
        "controls": [
            "5.9", "5.10", "5.11", "5.15", "5.16", "5.17", "5.18",
            "6.1", "6.2", "6.5", "8.2", "8.5",
        ],
    },
    "Art. 21(2)(j) – MFA & sichere Kommunikation": {
        "beschreibung": "Multi-Faktor-Authentifizierung, gesicherte Sprach-/Video-/Textkommunikation",
        "controls": ["5.14", "8.5", "8.20"],
    },
}

CONTROL_NAMES = {
    "5.1":  "Richtlinien für Informationssicherheit",
    "5.2":  "Rollen und Verantwortlichkeiten für IS",
    "5.3":  "Aufgabentrennung",
    "5.9":  "Inventar von Informationen und anderen Assets",
    "5.10": "Zulässige Nutzung von Informationen und anderen Assets",
    "5.11": "Rückgabe von Assets",
    "5.14": "Informationsübertragung",
    "5.15": "Zugangssteuerung",
    "5.16": "Identitätsverwaltung",
    "5.17": "Authentifizierungsinformationen",
    "5.18": "Zugriffsrechte",
    "5.19": "Informationssicherheit in Lieferantenbeziehungen",
    "5.20": "IS in Vereinbarungen mit Lieferanten",
    "5.21": "IS in der IKT-Lieferkette",
    "5.22": "Überwachung, Überprüfung und Änderungsmanagement von Lieferantendienstleistungen",
    "5.23": "IS für Nutzung von Cloud-Diensten",
    "5.24": "Planung und Vorbereitung des IS-Incident-Managements",
    "5.25": "Beurteilung und Entscheidung über IS-Ereignisse",
    "5.26": "Reaktion auf IS-Vorfälle",
    "5.27": "Aus IS-Vorfällen lernen",
    "5.28": "Beweissicherung",
    "5.29": "IS während Unterbrechungen",
    "5.30": "IKT-Bereitschaft für Business Continuity",
    "5.35": "Unabhängige Überprüfung der IS",
    "5.36": "Einhaltung von IS-Richtlinien, -regeln und -standards",
    "6.1":  "Sicherheitsüberprüfung",
    "6.2":  "Beschäftigungsbedingungen",
    "6.3":  "Sensibilisierung, Ausbildung und Schulung zur IS",
    "6.5":  "Verantwortlichkeiten nach Beendigung oder Wechsel des Beschäftigungsverhältnisses",
    "6.8":  "Meldung von IS-Ereignissen",
    "8.2":  "Privilegierte Zugriffsrechte",
    "8.3":  "Einschränkung des Informationszugriffs",
    "8.5":  "Sichere Authentifizierung",
    "8.8":  "Management von technischen Schwachstellen",
    "8.13": "Datensicherung",
    "8.14": "Redundanz von informationsverarbeitenden Einrichtungen",
    "8.20": "Netzwerksicherheit",
    "8.24": "Einsatz von Kryptographie",
    "8.25": "Sicherer Entwicklungslebenszyklus",
    "8.26": "Anforderungen an die Anwendungssicherheit",
    "8.27": "Sichere Systemarchitektur und technische Grundsätze",
    "8.28": "Sicheres Codieren",
    "8.29": "Sicherheitstests in Entwicklung und Abnahme",
    "8.30": "Ausgelagerte Entwicklung",
    "8.31": "Trennung von Entwicklungs-, Test- und Produktionsumgebungen",
    "8.32": "Änderungsmanagement",
    "9.1":  "Überwachung, Messung, Analyse und Bewertung",
}
